/**
 * Illustration map for Deep Learning with Python.
 *
 * Maps string IDs (used in lesson content's `illustrations` arrays) to React
 * components that render the corresponding SVG diagram.
 */

import type { ComponentType } from 'react';
import {
  // Module 1
  ConcentricCirclesDiagram,
  ParadigmShiftDiagram,
  AITimelineDiagram,
  ThreeIngredientsCard,
  SelfSupervisedLearningDiagram,
  CoordinateTransformDiagram,
  TrainingLoopDiagram,
  DLRevolutionDiagram,
  HypeCycleDiagram,
  MNISTNetworkDiagram,
  TensorRankDiagram,
  HigherRankTensorsDiagram,
  DataBatchDiagram,
  BroadcastingDiagram,
  ElementWiseOpsDiagram,
  TensorProductDiagram,
  GeometricInterpretationDiagram,
  GradientDescentDiagram,
  DerivativeSlopeDiagram,
  SgdVariantsDiagram,
  BackpropagationFlowDiagram,
  LayeredRepresentationsDiagram,
  HypothesisSpaceDiagram,
  // Module 2
  FrameworkStackDiagram,
  TFvsPyTorchDiagram,
  GradientTapeFlowDiagram,
  LinearClassifierDiagram,
  PyTorchModuleDiagram,
  JAXTransformsDiagram,
  KerasWorkflowDiagram,
  OverfittingDiagram,
  MultiHotEncodingDiagram,
  BinaryClassifierArchDiagram,
  SoftmaxDiagram,
  OneHotEncodingDiagram,
  RegressionDiagram,
  // Module 3
  LossLandscapeDiagram,
  ManifoldHypothesisDiagram,
  ManifoldInterpolationDiagram,
  KFoldValidationDiagram,
  ThreeWayDataSplitDiagram,
  EvaluationPitfallsDiagram,
  EarlyStoppingDiagram,
  ArchitecturePriorsDiagram,
  ModelCapacitySpectrumDiagram,
  ScaleUpToOverfitDiagram,
  DatasetCurationDiagram,
  FeatureEngineeringDiagram,
  RegularizationDiagram,
  WeightRegularizationDiagram,
  UnderfittingOverfittingDiagram,
  HyperparamSearchDiagram,
  MLWorkflowDiagram,
  MlLifecycleDiagram,
  // Module 4
  KerasAPIsDiagram,
  CallbacksDiagram,
  ConvolutionDiagram,
  MaxPoolingDiagram,
  SpatialHierarchyDiagram,
  ConvNetPyramidDiagram,
  DataAugmentationDiagram,
  TransferLearningDiagram,
  FineTuningDiagram,
  ResidualConnectionDiagram,
  BatchNormDiagram,
  DepthwiseSeparableConvDiagram,
  VisionTransformerPatchDiagram,
  // Module 5
  FeatureExtractionDiagram,
  GradCAMDiagram,
  EncoderDecoderDiagram,
  SegmentationTypesDiagram,
  YOLODiagram,
  NonMaxSuppressionDiagram,
  TimeseriesBaselineDiagram,
  ReceptiveFieldGrowthDiagram,
  CyclicalEncodingDiagram,
  RNNUnrolledDiagram,
  ReturnSequencesDiagram,
  BidirectionalRNNDiagram,
  RecurrentDropoutDiagram,
  // Module 6
  TokenizationPipelineDiagram,
  BpeMergingDiagram,
  WordEmbeddingDiagram,
  BagOfWordsVsSequenceDiagram,
  NextTokenPredictionDiagram,
  AutoregressiveGenDiagram,
  AttentionMechanismDiagram,
  PositionalEncodingDiagram,
  TransformerBlockDiagram,
  BERTvsGPTDiagram,
  NlpFineTuningDiagram,
  SamplingStrategiesDiagram,
  GPTArchitectureDiagram,
  LlmTrainingPipelineDiagram,
  MultimodalLlmDiagram,
  LoRADiagram,
  RAGDiagram,
  VAELatentSpaceDiagram,
  VaeLossDiagram,
  DiffusionProcessDiagram,
  IterativeDenoisingDiagram,
  TextToImageDiagram,
  // Module 7
  ModelEnsemblingDiagram,
  DataParallelismDiagram,
  QuantizationDiagram,
  QuantizationMemoryDiagram,
  DLLimitationsDiagram,
  LocalVsExtremeGenDiagram,
} from '@/components/illustrations';

export type IllustrationMap = Record<string, ComponentType<{ className?: string }>>;

const illustrationMap: IllustrationMap = {
  // Module 1
  'concentric-circles': ConcentricCirclesDiagram,
  'paradigm-shift': ParadigmShiftDiagram,
  'ai-timeline': AITimelineDiagram,
  'three-ingredients': ThreeIngredientsCard,
  'self-supervised-learning': SelfSupervisedLearningDiagram,
  'coordinate-transform': CoordinateTransformDiagram,
  'training-loop': TrainingLoopDiagram,
  'dl-revolution': DLRevolutionDiagram,
  'hype-cycle': HypeCycleDiagram,
  'mnist-network': MNISTNetworkDiagram,
  'tensor-rank': TensorRankDiagram,
  'higher-rank-tensors': HigherRankTensorsDiagram,
  'data-batch': DataBatchDiagram,
  'broadcasting': BroadcastingDiagram,
  'element-wise-ops': ElementWiseOpsDiagram,
  'tensor-product': TensorProductDiagram,
  'geometric-interpretation': GeometricInterpretationDiagram,
  'gradient-descent': GradientDescentDiagram,
  'derivative-slope': DerivativeSlopeDiagram,
  'sgd-variants': SgdVariantsDiagram,
  'backpropagation-flow': BackpropagationFlowDiagram,
  'layered-representations': LayeredRepresentationsDiagram,
  'hypothesis-space': HypothesisSpaceDiagram,
  // Module 2
  'framework-stack': FrameworkStackDiagram,
  'tf-vs-pytorch': TFvsPyTorchDiagram,
  'gradient-tape-flow': GradientTapeFlowDiagram,
  'linear-classifier': LinearClassifierDiagram,
  'pytorch-module': PyTorchModuleDiagram,
  'jax-transforms': JAXTransformsDiagram,
  'keras-workflow': KerasWorkflowDiagram,
  'overfitting': OverfittingDiagram,
  'multi-hot-encoding': MultiHotEncodingDiagram,
  'binary-classifier-arch': BinaryClassifierArchDiagram,
  'softmax': SoftmaxDiagram,
  'one-hot-encoding': OneHotEncodingDiagram,
  'regression': RegressionDiagram,
  // Module 3
  'loss-landscape': LossLandscapeDiagram,
  'manifold-hypothesis': ManifoldHypothesisDiagram,
  'manifold-interpolation': ManifoldInterpolationDiagram,
  'k-fold-validation': KFoldValidationDiagram,
  'three-way-data-split': ThreeWayDataSplitDiagram,
  'evaluation-pitfalls': EvaluationPitfallsDiagram,
  'early-stopping': EarlyStoppingDiagram,
  'architecture-priors': ArchitecturePriorsDiagram,
  'model-capacity-spectrum': ModelCapacitySpectrumDiagram,
  'scale-up-to-overfit': ScaleUpToOverfitDiagram,
  'dataset-curation': DatasetCurationDiagram,
  'feature-engineering': FeatureEngineeringDiagram,
  'regularization': RegularizationDiagram,
  'weight-regularization': WeightRegularizationDiagram,
  'underfitting-overfitting': UnderfittingOverfittingDiagram,
  'hyperparam-search': HyperparamSearchDiagram,
  'ml-workflow': MLWorkflowDiagram,
  'ml-lifecycle': MlLifecycleDiagram,
  // Module 4
  'keras-apis': KerasAPIsDiagram,
  'callbacks': CallbacksDiagram,
  'convolution': ConvolutionDiagram,
  'max-pooling': MaxPoolingDiagram,
  'spatial-hierarchy': SpatialHierarchyDiagram,
  'convnet-pyramid': ConvNetPyramidDiagram,
  'data-augmentation': DataAugmentationDiagram,
  'transfer-learning': TransferLearningDiagram,
  'fine-tuning': FineTuningDiagram,
  'residual-connection': ResidualConnectionDiagram,
  'batch-norm': BatchNormDiagram,
  'depthwise-separable-conv': DepthwiseSeparableConvDiagram,
  'vision-transformer-patch': VisionTransformerPatchDiagram,
  // Module 5
  'feature-extraction': FeatureExtractionDiagram,
  'grad-cam': GradCAMDiagram,
  'encoder-decoder': EncoderDecoderDiagram,
  'segmentation-types': SegmentationTypesDiagram,
  'yolo': YOLODiagram,
  'non-max-suppression': NonMaxSuppressionDiagram,
  'timeseries-baseline': TimeseriesBaselineDiagram,
  'receptive-field-growth': ReceptiveFieldGrowthDiagram,
  'cyclical-encoding': CyclicalEncodingDiagram,
  'rnn-unrolled': RNNUnrolledDiagram,
  'return-sequences': ReturnSequencesDiagram,
  'bidirectional-rnn': BidirectionalRNNDiagram,
  'recurrent-dropout': RecurrentDropoutDiagram,
  // Module 6
  'tokenization-pipeline': TokenizationPipelineDiagram,
  'bpe-merging': BpeMergingDiagram,
  'word-embedding': WordEmbeddingDiagram,
  'bag-of-words-vs-sequence': BagOfWordsVsSequenceDiagram,
  'next-token-prediction': NextTokenPredictionDiagram,
  'autoregressive-gen': AutoregressiveGenDiagram,
  'attention-mechanism': AttentionMechanismDiagram,
  'positional-encoding': PositionalEncodingDiagram,
  'transformer-block': TransformerBlockDiagram,
  'bert-vs-gpt': BERTvsGPTDiagram,
  'nlp-fine-tuning': NlpFineTuningDiagram,
  'sampling-strategies': SamplingStrategiesDiagram,
  'gpt-architecture': GPTArchitectureDiagram,
  'llm-training-pipeline': LlmTrainingPipelineDiagram,
  'multimodal-llm': MultimodalLlmDiagram,
  'lora': LoRADiagram,
  'rag': RAGDiagram,
  'vae-latent-space': VAELatentSpaceDiagram,
  'vae-loss': VaeLossDiagram,
  'diffusion-process': DiffusionProcessDiagram,
  'iterative-denoising': IterativeDenoisingDiagram,
  'text-to-image': TextToImageDiagram,
  // Module 7
  'model-ensembling': ModelEnsemblingDiagram,
  'data-parallelism': DataParallelismDiagram,
  'quantization': QuantizationDiagram,
  'quantization-memory': QuantizationMemoryDiagram,
  'dl-limitations': DLLimitationsDiagram,
  'local-vs-extreme-gen': LocalVsExtremeGenDiagram,
};

export default illustrationMap;
